name: barcode_parser
description: A Flutter package to parse barcodes.
version: 0.2.0
homepage: https://github.com/svprdga/barcode-parser

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  validators: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: 1.8.2

flutter: